### ISSUE TITLE
Format tokens are incoherent with builtin .Net tokens

### ISSUE THREAD

**Issue by GerkinDev** [dustout/BlazorTime#2]
Hi,

Some tokens for the format does not match the .Net specifications.

https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

For example, `MM` means *month* when using DateTime.ToString(), but *minutes* in your package
For `mm`, this is the inverse.

**Comment by dustout** [comment]
I am using the below library for the final display of the time, while it does not adhere to the .net spec I would rather not modify the library to maintain compatibility should the library need to be updated in the future. 

https://github.com/felixge/node-dateformat
